pipeline:
  notify: 
    image: vallard/drone-spark
    #room: "📦🔗 IOT"
    environment:
      - https_proxy=proxy.esl.cisco.com:80
      - http_proxy=proxy.esl.cisco.com:80
    secrets: [ SPARK_TOKEN ]
    when:
      status: [success, failure]
